services:
  server:
    image: prim/lsx-server:1.0.0
    build:
      context: "."
    restart: always
    container_name: "lsx_server"
    ports:
      - "${LSX_SERVER_PORT:-3005}:4005"
    # devices:
    #   - "/dev/snd:/dev/snd"

    environment:
      - QLCPLUS_WS_URL=${QLCPLUS_WS_URL:-ws://localhost:9999/qlcplusWS}
      - PHOBOS_AUTH_URL=${PHOBOS_AUTH_URL}
      - LSX_SERVER_HOSTNAME=${LSX_SERVER_HOSTNAME}
      - LSX_SERVER_PORT=${LSX_SERVER_PORT:-3005}
