apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alsa-config
data:
  asound.conf: |
{{- if eq .Values.audio.host "linux" }}
{{ .Files.Get "configs/alsa/asound.linux.conf" | indent 4 }}
{{- else }}
{{ .Files.Get "configs/alsa/asound.wsl.conf" | indent 4 }}
{{- end }}