apiVersion: apps/v1
kind: Deployment
metadata:
  name: phobos-lsx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phobos-lsx
  template:
    metadata:
      labels:
        app: phobos-lsx
    spec:
      containers:
      - name: phobos-lsx
        image: "prim/phobos-lsx:{{ .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005
        volumeMounts:
        - name: audio-devices
          mountPath: /dev/snd
        securityContext:
          allowPrivilegeEscalation: false 
          runAsUser: 1000 
          runAsGroup: 29
          capabilities:
            add:
              - SYS_RAWIO 
      volumes:
      - name: audio-devices
        hostPath:
          path: /dev/snd
          type: Directory 