apiVersion: v1
kind: Service
metadata:
  name: phobos-lsx-service
  labels:
    type: mfe
    name: phobos-lsx
spec:
  selector:
    app: phobos-lsx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000